### ISSUE TITLE
Bypass permission not working as expected

### ISSUE THREAD

**Issue by BetTD** [ds58/Panilla#104]
I was just trying out Panilla, compiled from source, on a 1.17.1 server running Pufferfish. I have the ``*`` permission node, as well as ``panilla.bypass`` explicitly. Tried creating a book with standard characters (2 pages long, first page was almost full), but I got kicked as soon as I pressed Done.

```
[11:05:25 WARN]: BetTD tried to send too large of a book. Book Size: 479 - Allowed:  336 - Pages: 2
[11:05:25 INFO]: BetTD lost connection: Book too large!
```

I do believe this to be a bug, as the bypass permission implies that I should be able to bypass all checks implemented by this plugin.

Could this be related to the fact that I compiled from the master branch instead of the latest release? There don't appear to be any changes that could've broken the permission check, but I did not look too closely at the commit history.

**Comment by ds58** [comment]
Does this kick happen without Panilla? This seems like a vanilla/paper protection

**Comment by BetTD** [comment]
I don't believe this happened before I installed Panilla, but I was also confused because I could not find the exact string in the plugin's source code. I'll spin up a test server and try it out.

**Comment by ds58** [comment]
Yep, that message comes from the server itself, not a plugin
