### ISSUE TITLE
does not allow you to enter the server

### ISSUE THREAD

**Issue by Fartumasti** [ds58/Panilla#107]
When trying to connect to the server, it immediately throws out
Internal Exception: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.Entity net.minecraft.world.entity.item.EntityItem.h()'

[2022-08-02-3.log](https://github.com/ds58/Panilla/files/9238335/2022-08-02-3.log)

**Comment by ds58** [comment]
Please reopen if this is still an issue. I am doing issue cleanup.
