### ISSUE TITLE
Panilla issues with Paper build #174 (Chunksystem Rewrite)

### ISSUE THREAD

**Issue by BlockyTheDev** [ds58/Panilla#112]
With Paper 1.19.2 Build #174 installed the plugin is throwing an exception. URL to ChunkSystem commit with the changes is attached at the end. At the moment I haven't access to the logs, but I taught I still need to report it today instead of tomorrow, because I saw a Github user reporting it at paper (and a PaperMC member wrote following into the issue: "Well it’s their responsibility to update. This is because they are using unsupported parts of the server."). URL is attached at the end, too. I hope I can help with opening this issue. 😄 

Commit: https://github.com/PaperMC/Paper/commit/01a13871deefa50e186a10b63f71c5e0459e7d30
Report to Paper: https://github.com/PaperMC/Paper/issues/8395

**Comment by ds58** [comment]
This has been fixed. Sorry for not updating this issue.
