### ISSUE TITLE
Newest paper build issues

### ISSUE THREAD

**Issue by Michael-A-Sloan** [ds58/Panilla#113]
Connecting to server issues. doesn't let you connect and states many different issues ranging from failed to verify username and from the screenshots I have here.

Here is two screen shots of possible things that happen when the Panilla plugin is loaded into the server.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/89812914/193187975-c8794539-44bf-4ccb-9227-011094219b6b.png">

![image](https://user-images.githubusercontent.com/89812914/193187994-4c7cddef-4606-4054-b550-91034acf9020.png)

**Comment by Folas1337** [comment]
Oh, convenient. I am having the same thing behind a velocity proxy and just repoted it on SpigotMC.
I'd like to see this resolved some time soon :)

**Comment by ds58** [comment]
This has been fixed. Sorry for not updating this issue.
