### ISSUE TITLE
Custom Name Item got NBT tag display failed checks

### ISSUE THREAD

**Issue by cupang-afk** [ds58/Panilla#117]
how to produce:
- get some item (commonly name_tag)
- rename it using anvil 
- drop the item

![image](https://user-images.githubusercontent.com/66926348/208291619-75c4cb00-be0b-40b2-a82e-df4765027e89.png)

my temp solution
- edit config.yml
- add `'display'` in `nbt-whitelist`
```
nbt-whitelist:
- 'display'
```

but it also disable lore checking because lore is part of display nbt alongside with item name
```
display:{Name:'[{"text":"Custom Item"}]',Lore:['[{"text":"Custom Lore"}]']}
```

**Comment by ds58** [comment]
Fixed in c605d6bd0d99d8fbec8582c65e7e77a2eac7f675. New release out on SpigotMC
