### ISSUE TITLE
Improperly removing shulker

### ISSUE THREAD

**Issue by SrBedrock** [ds58/Panilla#126]
The plugin is removing valid shulker from the player's inventory or ender chest, shulker with various renamed items and with custom lore that are not dangerous and should not be removed.

**Comment by ds58** [comment]
Thanks for reporting. I'll look at this soon

**Comment by pjindras** [comment]
I have the same issue, i must restore backup and remove plugin because lots of players lost items, please fix it soon.

**Comment by ds58** [comment]
What's happening is I treat shulkerbox NBT as a whole. So if one item within the shulkerbox is considered "bad" then the whole shulkerbox NBT is flagged and reset. I'll have to do a smarter approach where I rewrite the shulkerbox NBT with the "bad" items removed. Will work on this today.

**Comment by ds58** [comment]
Try the latest release `1.9.0`. I added a compromise which I believe will address this situation
