### ISSUE TITLE
Plugins' menus cleaned by Panilla

### ISSUE THREAD

**Issue by angushushu** [ds58/Panilla#134]
Hi, our server includes multiple plugins using the chest menu for GUI such as [DeluxeMenu](https://www.spigotmc.org/resources/deluxemenus.11734/), [Adapt](https://www.spigotmc.org/resources/adapt-leveling-skills-and-abilities.103790/), [Playertask](https://www.spigotmc.org/resources/%E2%AD%90-playertask-%E2%AD%90-%E4%B8%A8%E3%80%8Crandom-task-%E3%80%8D-custom-interface-compatible-citizen.96554/), etc.
Panilla will clean the menu sometime with
```
[Panilla] Packet of type PacketPlayOutSetSlot to player <playername> was dropped because NBT tag HideFlags failed checks
```
Expected view (what OPs see):
![image](https://github.com/ds58/Panilla/assets/23127549/50af7218-d540-4b92-8f3e-638635be22ba)
What players see:
![image](https://github.com/ds58/Panilla/assets/23127549/2be0cadc-00aa-44b3-a8cf-0ae3fcda4b48)

a .log file is attached, you can search for "/Adapt gui [Main]"
[latest.log](https://github.com/ds58/Panilla/files/12338883/latest.log)

**Comment by ds58** [comment]
Hi,

You can try a couple different configuration options to avoid this:

```
ignore-non-player-inventories: true
```
```
nbt-whitelist:
  - HideFlags
```

**Comment by angushushu** [comment]
> Hi,
> 
> You can try a couple different configuration options to avoid this:
> 
> ```
> ignore-non-player-inventories: true
> ```
> 
> ```
> nbt-whitelist:
>   - HideFlags
> ```

Thanks a lot, I should have checked the config file carefully. The ignore-non-player-inventories option works well!
