### ISSUE TITLE
Please update to 1.20.6/1.21

### ISSUE THREAD

**Issue by TWME-TW** [ds58/Panilla#149]
Please update to 1.20.6/1.21

**Comment by ArZorMC** [comment]
Looking forward to an update for 1.21 too. 
When I attempted to load the plugin on a Paper version 1.21-99 server I got the following error:
https://hastebin.skyra.pw/owopuhacoh.pgsql

**Comment by TWME-TW** [comment]
> Looking forward to an update for 1.21 too. When I attempted to load the plugin on a Paper version 1.21-99 server I got the following error: https://hastebin.skyra.pw/owopuhacoh.pgsql

I've asked someone else to do the update (I asked him to update to 1.20.6), maybe he will finish it in 1 or 2 weeks

**Comment by Nielsbest** [comment]
@TWME-TW Did he finish the 1.20.6 update?

**Comment by fadfhkdfga** [comment]
1.21 update plz

**Comment by ds58** [comment]
1.20.6 and 1.21/1.21.1 are now supported on **Paper** in the latest release.
