### ISSUE TITLE
Custom skull check error

### ISSUE THREAD

**Issue by TWME-TW** [ds58/Panilla#163]
In the latest version, this plugin treats all heads as incorrect items.

How to reproduce: Use the headdatabase and try to get the head

Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

Panilla version 1.12.2

**Comment by ds58** [comment]
Should be fixed in `1.12.3`
