### ISSUE TITLE
Chests with NBT

### ISSUE THREAD

**Issue by x1p** [ds58/Panilla#65]
I have dealed with something like in this video: https://www.youtube.com/watch?v=JDGx8zeCsUA

I don't like chests with NBT data in peoples inventory (video at 1.00 minute)
I certainly don't like shulkers with chests (+NBT)  in it  (video at 1.10 minute)

How can I prevent this?
I tried strict, but it didn't block it.

I think there are similarity's with issue #64 but I'm not sure.

**Comment by dextonanderson** [comment]
Hi,

Currently Panilla does attempt to identify these types of "crash chests" and block them.

Here is me performing a quick test: https://www.youtube.com/watch?v=EXeaWz3HW0M

**Comment by dextonanderson** [comment]
Also, to note, this would also be the same case if you filled a Shulker Box with these same books.

**Comment by x1p** [comment]
For now I found a plugin which blocks copying stuff with nbt tags

**Comment by ds58** [comment]
Please reopen if this is still an issue. I am doing issue cleanup.
