### ISSUE TITLE
Kicks when connecting to the server

### ISSUE THREAD

**Issue by DenisJ9798** [ds58/Panilla#75]
PaperSpigot 1.16.5
Panilla 1.6.4
[19:19:59] [Server thread/INFO]: 2012Kirill1104 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Data not read fully, bytes left 24

**Comment by dextonanderson** [comment]
Hi,

Please try this build of Panilla. It should fix the issue. I will be making a SpigotMC release soon.
[Panilla.zip](https://github.com/Ruinscraft/Panilla/files/6132064/Panilla.zip)

**Comment by DenisJ9798** [comment]
> Hi,
> 
> Please try this build of Panilla. It should fix the issue. I will be making a SpigotMC release soon.
> [Panilla.zip](https://github.com/Ruinscraft/Panilla/files/6132064/Panilla.zip)

Checked, the problem remains

**Comment by dextonanderson** [comment]
Is this still an issue?

**Comment by blockswerker** [comment]
This is still an issue for me, using Panilla 1.7.2.

**Comment by ds58** [comment]
Please reopen if this is still an issue. I am doing issue cleanup.
