### ISSUE TITLE
Panilla execptions and tps drops with crashers guys

### ISSUE THREAD

**Issue by Malachiel87** [ds58/Panilla#91]
https://timings.aikar.co/?id=26723260cccd475bb4103c74d188574e
I see my server there are a lot of chestcracher and tps keep to going down a lot i am using 1.17.1 paper
plus trìowing a lot of exceptions,full log:
[latest.log](https://github.com/Ruinscraft/Panilla/files/6872615/latest.log)

**Comment by ds58** [comment]
Please reopen if this is still an issue. I am doing issue cleanup.
