### ISSUE TITLE
Feature Request - block "nested NBTs" (crossbow loaded with scuffed arrow)

### ISSUE THREAD

**Issue by vance13** [ds58/Panilla#93]
players are able to obtain illegal effects because a crossbow loaded with an illegal arrow is not blocked. Here is what the item looks like when written to yml:

- ==: org.bukkit.inventory.ItemStack
      v: 2586
      type: CROSSBOW
      meta:
        ==: ItemMeta
        meta-type: CROSSBOW
        display-name: '{"text":"neptune''s 32k crossy!"}'
        enchants:
          MULTISHOT: 1
        charged: true
        charged-projectiles:
        - ==: org.bukkit.inventory.ItemStack
          v: 2586
          type: TIPPED_ARROW
          meta:
            ==: ItemMeta
            meta-type: POTION
            potion-type: minecraft:long_slow_falling
            custom-color:
              ==: Color
              RED: 114
              BLUE: 255
              GREEN: 43
            custom-effects:
            - ==: PotionEffect
              effect: 2
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 4
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 8
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 9
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 15
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 17
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 18
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 19
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 20
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 24
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 25
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 27
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 28
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 31
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
        - ==: org.bukkit.inventory.ItemStack
          v: 2586
          type: TIPPED_ARROW
          meta:
            ==: ItemMeta
            meta-type: POTION
            potion-type: minecraft:long_slow_falling
            custom-color:
              ==: Color
              RED: 114
              BLUE: 255
              GREEN: 43
            custom-effects:
            - ==: PotionEffect
              effect: 2
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 4
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 8
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 9
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 15
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 17
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 18
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 19
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 20
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 24
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 25
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 27
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 28
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 31
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
        - ==: org.bukkit.inventory.ItemStack
          v: 2586
          type: TIPPED_ARROW
          meta:
            ==: ItemMeta
            meta-type: POTION
            potion-type: minecraft:long_slow_falling
            custom-color:
              ==: Color
              RED: 114
              BLUE: 255
              GREEN: 43
            custom-effects:
            - ==: PotionEffect
              effect: 2
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 4
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 8
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 9
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 15
              duration: 2000000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 17
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 18
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 19
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 20
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 24
              duration: 100000
              amplifier: 1
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 25
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 27
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 28
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true
            - ==: PotionEffect
              effect: 31
              duration: 2000000
              amplifier: 92
              ambient: false
              has-particles: true
              has-icon: true

Thanks for reading :)

**Comment by ds58** [comment]
If this is still an issue, please reopen. I am doing issue cleanup.
