### ISSUE TITLE
Dispenser/Dropper ShulkerChest behaviour broken

### ISSUE THREAD

**Issue by Tiippex** [ds58/Panilla#95]
Hello,

I have some issues with ShulkerChests within droppers and dispensers. It is not possible to drop/dispense ShulkerChests.

There are no errors or alerts in the console.

Gamemode: Creative
Paper:  git-Paper-188 (MC: 1.17.1)
Panilla: 1.7.2

**Comment by MrEDok** [comment]
This issue still happen in 1.18 version of the plugin.

**Comment by Dreeam-qwq** [comment]
same issue, I tested on 1.18.1
I think that it is the problem of this part of code.
https://github.com/Ruinscraft/Panilla/blob/441cb3935dc9db134644eb5c0a3c036bfad7af13/bukkit/src/main/java/com/ruinscraft/panilla/bukkit/TileLootTableListener.java#L64

**Comment by blockswerker** [comment]
Is this something that could be added as an option to the config?

**Comment by lululombard** [comment]
Still an issue on 1.19.2

**Comment by ds58** [comment]
Should be fixed with 09113fbd96c18399af7b320ff2980867916fbd08
